version: "3.8"

networks:
    escola_net:
        driver: bridge
services:
    db:
        env_file: ./.env
        image: postgres:alpine
        restart: always
        container_name: escola_db
        networks:
            - escola_net
        environment: 
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}  
        volumes:
            - ${DB_DATA_PATH}:/var/lib/postgresql/data
    web:
        env_file: ./.env
        image: escola/web
        build:
            context: ./escola
        container_name: escola_web
        ports:
            - "${HOST_HTTP_DEV_PORT}:8000"
        networks:
            - escola_net
        entrypoint: ["sh","/app/escola/entrypoint.sh"]
        volumes:
            - ./escola:/app/escola
            - ${STATICFILES_PATH}:/app/staticfiles
            - ${MEDIA_PATH}:/app/media
        depends_on:
            - db
        links: 
            - db
    proxy:
        env_file: ./.env
        image: escola/proxy
        build:
            context: ./proxy
        container_name: escola_proxy
        networks:
            - escola_net
        ports:
            - "${HOST_HTTP_PORT}:80"
        environment:
            - NGINX_PORT=80
        volumes: 
            - ${STATICFILES_PATH}:/escola/staticfiles
            - ${MEDIA_PATH}:/escola/media
        depends_on: 
            - web
